### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by steini72** [Ziyatoe/DTUsimMI1x00-Hoymiles#6]
NRF24_DTUMIesp:164:89: error: cannot pass objects of non-trivially-copyable type 'const class String' through '...'
       if (!p) DEBUG_OUT.printf("%sRFRxPacket:%s packetbuffer getFront full\r\n",LON,LOFF);

**Comment by Ziyatoe** [comment]
hi, could you give me the console log?

**Comment by steini72** [comment]
Was at RF24 1.4.6 with RF24 1.4.2 it works

**Comment by Ziyatoe** [comment]
ok
