### ISSUE TITLE
Benötige Hilfe

### ISSUE THREAD

**Issue by guergen1** [Ziyatoe/DTUsimMI1x00-Hoymiles#7]
Hi, wie baue ich das Programm hier zusammen? Habe irgendwie gefühlt nur ein Bruchteil von dem was Arduino von mir haben will...
Vielleicht kannst du ja helfen.
Ich verstehe das ja richtig, dass man damit die Daten einem Mi300 auslesen können soll, oder?

**Comment by Ziyatoe** [comment]
ja, wie beschrieben für die MI serie.
auf arduino habe es nur bis auf version 1.0.0 getested, danach nur für esp8266.
wo hacks denn?

**Comment by guergen1** [comment]
Hab es mit Arduiono IDE und VSC veruscht... Habe hier einen MI-300 und nen ESP8266. Ich muss ja mittels VisualStudioCode aus dem Code ein Programm coden. Wenn ich das in VVSC einlese meckert das Programm, dass diverse codes fehlen. Welche muss ich denn woher holen, damit ich da ein Programm draus bekomme?

**Comment by Ziyatoe** [comment]
verwende  ARDUINO IDE zum das ESP8266 laden, nicht vsc! 
es steht ja im readme: You need ArduinoIDE for this skecth! tested with arduino-ide 2.0.0-rc6 und 1.8.19

**Comment by guergen1** [comment]
Ja, aber da bekomme ich Fehler: RF24.h: No such file or directory
Auch das File RF24_config.h ist nicht im Verzeichnis.
Muss secrets_ANPASSEN wieder umbenannt werden?
Welche der beine .ino-Dateine muss ich denn nutzen,NRF24_DTUMlesp.ino oder  die Datei inm sniffer-Verzeichnis?

**Comment by guergen1** [comment]
So langsam kome ich dahinter. Allerdings finde ich keine debug_macro.h und Arduino meckert, dass es mehrere "CircularBuffer.h" findet...

**Comment by Ziyatoe** [comment]
das problem ist deine arduino-ide findet die libraries nicht, oder doppelt,
muss die arduino umgebung prüfen und die richtige libraries laden.
alle include's im *.ino müssen als library vorhanden sein, eigentlich es
ist nicht so kompliziert

Am Sa., 31. Dez. 2022 um 16:14 Uhr schrieb guergen1 <
***@***.***>:

**Comment by Ziyatoe** [comment]
> Ja, aber da bekomme ich Fehler: RF24.h: No such file or directory Auch das File RF24_config.h ist nicht im Verzeichnis. Muss secrets_ANPASSEN wieder umbenannt werden? Welche der beine .ino-Dateine muss ich denn nutzen,NRF24_DTUMlesp.ino oder die Datei inm sniffer-Verzeichnis?

- RF24.h ist eine ext. library, muss in der arduino-ide vorhanden sen
- sniffer ist wie drauf steht ein standalone-sniffer! du willst doch die DTU oder?
- secret_ANPASSEN, ja , wenn du include anschauest, dort steht doch secret.h

**Comment by guergen1** [comment]
>     * RF24.h ist eine ext. library, muss in der arduino-ide vorhanden sen

Die habe ich mittlerweile
 
>     * sniffer ist wie drauf steht ein standalone-sniffer! du willst doch die DTU oder?

Ja, ich möchte die DTU

>     * secret_ANPASSEN, ja , wenn du include anschauest, dort steht doch secret.h

Hab ich schon gedacht, läuft soweit. Aber nur, wenn ich die secrets.h in ein ZIP-File packe, liegt das im normalen Verzeichnis, findet Arduino es nicht

Allerdings hat das Programm jetzt keine debug_macro.h und mehrere CircularBuffer.h
Steigt aus mit Exit Status 1

**Comment by guergen1** [comment]
Ich gebe es auf... das ist ja ein zusammengesuche und ein hin und herkopiere...
Vielleicht bin ich einfach zu alt für den Scheiss....

**Comment by Ziyatoe** [comment]
> 

wenn du "saubere" arduino-ide hast und die nrf24 library vorhanden ist, braucht es keine kopiererei!
wozu " Aber nur, wenn ich die secrets.h in ein ZIP-File packe"????
alle sources in einem ordner auspacken, dann musst du nur das secret.h anpassen, einfacher gehts nicht.

**Comment by guergen1** [comment]
Wahrscheinlich habe ich keine saubere Installation mehr... 
Wenn ich alles lösche, ArduinoIDE in der Version 1.8.6, sowie die librarys die ich die Tage geladen habe, müsste ich alles wieder los sein. 
Dann ArduionIDE wieder neu laden.
Erste Fehlermeldung:
`Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Uno"
NRF24_DTUMIesp:1:10: fatal error: nRF24L01.h: No such file or directory
 #include <nRF24L01.h>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
nRF24L01.h: No such file or directory
Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`
In der Bibliotheksverwaltung RF24 in der Version 1.4.6 installiert

Nächste Fehlermeldung:
`Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Uno"
NRF24_DTUMIesp:28:10: fatal error: Settings.h: No such file or directory
 #include "Settings.h"
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Settings.h: No such file or directory
Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`
Die Datei ist aber doch in dem Verzeichnis!
Dann die Setiings.h manuell hinzugefügt. Jetzt kommt die Fehelrmeldung, dass Pinger.h fehlt.
Ich lasse es bleiben!
Danke für die Hilfe und Geduld!

**Comment by Ziyatoe** [comment]
- wo ist im source, die zeile #include <nRF24L01.h> ?? das gibts bei mir nicht
  es ist und sollte im *.ino file nur #include <RF24.h> sein, 
  ich sehe dass du mit windows arbeitest, ist echt deine umgebungs variablen für arduinp richtig gesetzt?
- pinger ist auch eine library
- settings.h (angepasst) muss im gleichen ordner sein

**Comment by guergen1** [comment]
Das ist schon sehr seltsam: ich habe jetzt zum 5. Mal alles gelöscht, mir die selben Librarys neu geladen.
Dann die Secrets und Settings angepasst; wie egtl. in allen Versuchen!
Neu übertragen und; was soll ich sagen;  es läuft....

Danke Dir für die Unterstützung!

PS.: Kan ich auch irgendwo ein MQTT-Passwort definieren? Ich hab jetzterstmal eine neue MQTT-Instanz ohne PW erstellt, geht zwar auch so, aber da sandere wäre sauberer.

**Comment by Ziyatoe** [comment]
das freut mich!!!
mqtt mit username/pw:
- in mqtt.h
- ab zeile 113 anpassen
mqttClient.setId(MQTTclientid);
mqttClient.setUsernamePassword("username", "password");  <<<<<<<<<<<<<<<<<
if (!mqttClient.connect(MQTTbroker, MQTTport)) {

**Comment by guergen1** [comment]
Danke, aber meine mqtt.h hat nur 104 Zeilen, ich habe das jetzt in Zeile 87 eingefügt, ob es passt, sehe ich morgen früh!
Aber am MQTT ist erschonmal angemeldet.

**Comment by Ziyatoe** [comment]
ok, wenns so weit ok ist kannst du bitte dieses issue schliessen?

**Comment by guergen1** [comment]
Das war mein Plan.

**Comment by guergen1** [comment]
Ein Frage hätte ich noch: die UIhrzeit stimmt nicht, timeZone ist 2 eingestellt. Bei 1 wäre sie richtig. Kann ich die einfach auf 1 umstellen, oder bringt das irgendwo was durcheinander?
Der Grund ist, dass der ESP um 8:45Uhr noch "is night time" angezeigt hat und ich daraufhin auf timeZone 1 gewechselt bin.
Sonnenaufgang wäre um 8:30 gewesen

**Comment by Ziyatoe** [comment]
timezone kannst du anpassen, wie es bei dir richtig waere

**Comment by guergen1** [comment]
Besten Dank!
