### ISSUE TITLE
9:45h---> is night time !?!

### ISSUE THREAD

**Issue by guergen1** [Ziyatoe/DTUsimMI1x00-Hoymiles#8]
Da ich ja jetzt erst auf deine Programmcodes aufmerksam geworden bin und es Dank Deiner Hilfe mittlerweile alles soweit funktioniert, habe ich noch eine weitere Frage:
Mein WR hängt noch an einer Leistungs-Messsteckdose, die zeigte mir heute  Aktivität des WR bereits ab 08:45h an. Die DTUsimMI stand aber etwa bis um 09:45 auf "is night time".
Kann ich die Zeit auch noch etwas anpassen?
Ich habe die Longitude schon etwas Richtung Süden verschoben, aber das hat nicht wirklich was gebracht.
Ich finde im Code auch nicht wirklich die Stelle, wo das abgearbeitet wird.
Noch etwas: kann ich die Senderate für die MQTT-Daten von 30 sek auf 10 sek setzen?
Auch wurden seit dem Einschlafen gestern bis zum Neustart grade eben keine MQTT-Daten mehr in die Datenbank gesendet. Die Web-Ansicht zeigte allerdings aktuelle Daten an:
![grafik](https://user-images.githubusercontent.com/34395245/211559136-560cc197-d1b8-46c7-b4c9-89a28069f1af.png)

**Comment by Ziyatoe** [comment]
es sollte gehen: im settings.h
#define  TIMEOFFSET 0   anpassen

(neben bei:
"Ich habe die Longitude schon etwas Richtung Süden verschoben", es sollte ost/west verschoben werden damit die zeit auch "verschoben" wird)

mqtt senderate wird nicht vorgegeben (ausser es ist nacht,es wird nichts gesendet), sobald die angeschlossene pv's erfasst werden, wird es gesendet

es gibt im settings.h #define REFRESH 30 für die http

**Comment by guergen1** [comment]
Dann muss ich mal schauen, wie ich die Nachtzeit verändern kann
Den Breitengrad habe ich deshalb verschoben, da ich dachte es wird über diese der SA-Winkel für meinen Wohnort berechnet. die Longitude kommt ja quasi schon aus der Zeitzone. 
Heute habe ich SunUP at 9.20 im Serial stehen, das ist etwa eine Stunde daneben obwohl Längen und Breitengrad passend eingestellt sind.
Ich glaube ich hab es gefunden: im sonne.h steht
`  //SunUpDown res = new SunUpDown();
  boolean isSummerTime = true`
da hab ich mal mit rumgespielt, false eingetragen und der Wert passt jetzt
